# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md", "LICENSE"]
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom Variables
analytics: 100943296
author:
  email: "sreenath.s@husky.neu.edu"
  github: "sreeram6791"
  linkedin: "mandikal"
  name: "Sreeram Mandikal Sreenath"
  uri: ""
description: "Personal website of Sreeram Sreenath, MS Information Systems."
title: "Sreeram Mandikal Sreenath"
url: ""